# Stage 1: Download all dependencies
FROM ubuntu:24.04 AS dependencies

ENV VCPKG_DISABLE_METRICS=1

RUN --mount=type=cache,target=/var/cache/apt \
	apt update && apt install -y --no-install-recommends cmake git \
	unzip build-essential ca-certificates curl zip unzip tar \
	pkg-config ninja-build autoconf automake libtool glibc-tools \
	python3 \
	&& apt clean \
	&& rm -rf /var/lib/apt/lists/*

WORKDIR /opt
COPY docker/vcpkg /opt/vcpkg

WORKDIR /opt/vcpkg
RUN git init
RUN git remote add origin https://github.com/microsoft/vcpkg.git
RUN git fetch origin

RUN ./bootstrap-vcpkg.sh

# RUN vcpkgCommitId=$(grep '.builtin-baseline' vcpkg.json | awk -F: '{print $2}' | tr -d '," ' | tr -d '\r\n') \
#     && echo "vcpkg commit ID: '$vcpkgCommitId'" \
#     && git clone https://github.com/microsoft/vcpkg.git \
#     && cd vcpkg \
#     && git fetch origin \
#     && git checkout "$vcpkgCommitId" \
#     && ./bootstrap-vcpkg.sh

COPY vcpkg.json /opt/vcpkg/
RUN --mount=type=cache,target=/var/cache/vcpkg \
	/opt/vcpkg/vcpkg --disable-metrics install

# Stage 2: create build
FROM dependencies AS build
WORKDIR /srv/build
COPY src ./src
COPY cmake ./cmake
COPY recompile.sh CMakeLists.txt CMakePresets.json vcpkg.json ./
RUN ./recompile.sh "/opt"

# Stage 3: execute
# FROM ubuntu:24.04 AS prod
# COPY --from=build /srv/build/canary /bin/canary
# WORKDIR /srv/canary
# VOLUME /canary
# ENTRYPOINT ["/srv/canary/start.sh", "canary"]

FROM scratch AS export-stage
COPY --from=build /srv/build/canary /canary
